# Generated by Django 5.2.7 on 2025-10-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TopStudent',
            fields=[
            ],
            options={
                'ordering': ['-marks'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.student',),
        ),
    ]
